config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  resources :tweets, only: [:index, :new, :create]

  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member 
  end
end
# , only: :show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
 
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
 
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to "/"
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header-contents">
        <div class="header-left">
          <h1 class="app-name"><a href="/">FollowApp</a></h1>
        </div>

        <div class="header-right">
          <% if user_signed_in? %>
              <a class="current-name" href="/users/<%= current_user.id %>">
                <%= current_user.nickname %>
              </a>
              <%= link_to "ログアウト", destroy_user_session_path,class: "btn", method: :delete %>
              <%= link_to  "投稿する", new_tweet_path, class: "btn" %>
          <% else %>
              <%= link_to "ログイン", new_user_session_path, class: "btn" %>
              <%= link_to "新規登録", new_user_registration_path, class: "btn" %>
          <% end %>
        </div>
      </div>
    </header>
      <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="t-form">
  <%= form.text_area :text, class: "t-text",placeholder: "text" , rows: "10" %>
  <%= form.submit "SEND" ,class:"btn"%>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <p class = "tweet-text"><%= tweet.text %></p>
  <div class="tweet-name">
    <% if user_signed_in? %>
      <a href="/users/<%= tweet.user.id %>">
        <span>投稿者：</span><%= tweet.user.nickname %>
     </a>
    <% else %>
      <a href="/users/sign_in">
        <span>投稿者：</span><%= tweet.user.nickname %>
      </a>
    <% end %>   
  </div>
</div>

app/views/tweets/index.html.erb
<div class = "tweets">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="tweet-form">
  <%= form_with(model: @tweet, local: true) do |form| %>
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { form: form } %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="followers">
  <h1><%= @user.nickname %>さんのフォロワー一覧</h1>
    <% @users.each do |user| %>
    <hr>
    <p class="f-user"><%= link_to user.nickname, user_path(user.id) %></p>
        <% if current_user != user && user.followed_by?(current_user) %>
            <p><%=link_to "フォロー中", user_relationships_path(user.id),class:"btn", method: :delete %></p>
        <% end %>
        <% if current_user != user && !user.followed_by?(current_user) %>
            <p><%=link_to "フォローする", user_relationships_path(user.id),class:"btn", method: :post %></p>
        <% end %>
    <% end %>
</div>

app/views/users/follows.html.erb
<div class="follows">
  <h1><%= @user.nickname %>さんのフォロー一覧</h1>
  <% @users.each do |user| %>
    <hr>
    <p class="f-user"><%= link_to user.nickname, user_path(user.id) %></p>
      <% if current_user != user && user.followed_by?(current_user) %>
          <p><%=link_to "フォロー中", user_relationships_path(user.id),class:"btn", method: :delete %></p>
      <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-page">
  <div class="user-contents">
    <p class="user-name"><%= @user.nickname %></p>

    <p><%=link_to "フォロー", follows_user_path(@user.id) ,class:"f-member" %></p>
    <p><%=link_to "フォロワー", followers_user_path(@user.id),class:"f-member" %></p>
    <% if current_user != @user && @user.followed_by?(current_user) %>
        <p><%=link_to "フォロー中", user_relationships_path(@user.id),class:"btn" , method: :delete %></p>
    <% end %>
    <% if current_user != @user && !@user.followed_by?(current_user) %>
        <p><%=link_to "フォローする", user_relationships_path(@user.id),class:"btn" ,method: :post %></p>
    <% end %>
  </div>
</div>